org.gradle.caching=true
#org.gradle.configureondemand=true
org.gradle.jvmargs=-Xmx4G -XX\:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
# https://github.com/google/play-services-plugins/issues/246
org.gradle.configuration-cache.problems=warn
org.gradle.parallel=true
# AndroidX
android.useAndroidX=true

# Enable non-transitive R Class
android.nonTransitiveRClass=true

android.defaults.buildfeatures.buildconfig=false
android.nonFinalResIds=false

kotlin.mpp.applyDefaultHierarchyTemplate=false
kotlin.native.ignoreDisabledTargets=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
