name: Android CI

on:
  push:
    branches: [ main ]
    tags:
      - v*
      - ci*
    paths-ignore:
      - '.idea/**'
  pull_request:
    branches: [ main, dev ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - uses: act10ns/slack@v1
        with:
          status: starting
          channel: '#watchdone'
        if: always()

      - name: Check Out
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PRIV_REPO_PAT }}
          submodules: 'recursive'

      - name: Get commit hash
        id: commithash
        shell: bash
        run: |
          sha=$( curl -u "u:${{github.token}}" https://api.github.com/repos/thesandipv/watchdone/git/ref/heads/${{ github.head_ref }} | jq .object.sha | tr -d '"' )
          if [ $sha == "null" ] || [ $sha == "" ]; then
            if [ ${{ github.ref_type }} == "branch" ]; then
              sha=$( curl -u "u:${{github.token}}" https://api.github.com/repos/thesandipv/watchdone/git/ref/heads/${{ github.ref_name }} | jq .object.sha | tr -d '"' )
            else
              sha=$( curl -u "u:${{github.token}}" https://api.github.com/repos/thesandipv/watchdone/git/ref/tags/${{ github.ref_name }} | jq .object.sha | tr -d '"' )
            fi
          fi
          echo $sha
          short_sha=${sha:0:7}
          echo $short_sha
          echo ::set-output name=sha::$sha
          echo ::set-output name=sha_short::$short_sha

      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permissions
        run: chmod +x release/decrypt.sh release/clean.sh

      - name: Decrypt Task
        run: ./release/decrypt.sh
        env:
          ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Cache Gradle
        uses: actions/cache@v2
        continue-on-error: true # continue if the cache restore/upload fails
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        env:
          CI: true
          GHTOKEN: ${{ secrets.GITHUB_TOKEN }}
          GHUSERNAME: ${{ secrets.GHUSERNAME }}
          SIGN_KEY_PW: ${{ secrets.SIGN_KEY_PW }}
          SIGN_STORE_PW: ${{ secrets.SIGN_STORE_PW }}
          TMDB_API: ${{ secrets.TMDB_API }}
          TMDB_BEARER_TOKEN: ${{ secrets.TMDB_BEARER_TOKEN }}
          COMMIT_ID: ${{ steps.commithash.outputs.sha_short }}
        with:
          arguments: :app:assemble :app:bundle :app:lintDebug :app:testDebug --stacktrace

      - name: Run Tests in app module
        uses: gradle/gradle-build-action@v2
        id: run-tests
        with:
          arguments: :app:test
        env:
          TMDB_API: ${{ secrets.TMDB_API }}
          TMDB_BEARER_TOKEN: ${{ secrets.TMDB_BEARER_TOKEN }}
          COMMIT_ID: ${{ steps.commithash.outputs.sha_short }}

      - name: Publish to Play Store
        if: startsWith(github.ref, 'refs/tags/v')
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: release/serviceAccount.json
          packageName: com.afterroot.watchdone
          track: internal
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          mappingFile: app/build/outputs/mapping/release/mapping.txt

      - name: Create release for tags
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          draft: true
          files: |
            app/build/outputs/apk/release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean Task
        if: always()
        run: ./release/clean.sh

      - name: Upload build outputs
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: app-release-apk
          path: app/build/outputs/apk/release/app-release.apk

      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: app-build-reports
          path: app/build/reports

      - name: Upload to Slack
        id: upload-to-slack
        uses: adrey/slack-file-upload-action@1.0.5
        with:
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          path: app/build/outputs/apk/release/app-release.apk
          channel: watchdone
          filename: Watchdone-${{ steps.commithash.outputs.sha_short }}.apk

      - uses: act10ns/slack@v1
        if: always()
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#watchdone'
